version: '3.3'

services:
  jpa-test-db:
    container_name: jpa-test-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d